export interface ConstituencyInfo {
  acNo: number;
  name: string;
  nameMl: string;
  district: string;
}

export const keralaConstituencies: Record<number, ConstituencyInfo> = {
  // KASARAGOD
  1: { acNo: 1, name: 'Manjeswaram', nameMl: 'മഞ്ചേശ്വരം', district: 'Kasaragod' },
  2: { acNo: 2, name: 'Kasaragod', nameMl: 'കാസർഗോഡ്', district: 'Kasaragod' },
  3: { acNo: 3, name: 'Udma', nameMl: 'ഉദുമ', district: 'Kasaragod' },
  4: { acNo: 4, name: 'Kanhangad', nameMl: 'കാഞ്ഞങ്ങാട്', district: 'Kasaragod' },
  5: { acNo: 5, name: 'Trikaripur', nameMl: 'തൃക്കരിപ്പൂർ', district: 'Kasaragod' },
  // KANNUR
  6: { acNo: 6, name: 'Payyannur', nameMl: 'പയ്യന്നൂർ', district: 'Kannur' },
  7: { acNo: 7, name: 'Kalliasseri', nameMl: 'കല്ല്യാശ്ശേരി', district: 'Kannur' },
  8: { acNo: 8, name: 'Thalassery', nameMl: 'തലശ്ശേരി', district: 'Kannur' },
  9: { acNo: 9, name: 'Dharmadom', nameMl: 'ധർമ്മടം', district: 'Kannur' },
  10: { acNo: 10, name: 'Iritty', nameMl: 'ഇരിട്ടി', district: 'Kannur' },
  11: { acNo: 11, name: 'Kuthuparamba', nameMl: 'കൂത്തുപറമ്പ്', district: 'Kannur' },
  12: { acNo: 12, name: 'Mattannur', nameMl: 'മട്ടന്നൂർ', district: 'Kannur' },
  13: { acNo: 13, name: 'Peravoor', nameMl: 'പേരാവൂർ', district: 'Kannur' },
  14: { acNo: 14, name: 'Azhikode', nameMl: 'ആഴിക്കോട്', district: 'Kannur' },
  15: { acNo: 15, name: 'Kannur', nameMl: 'കണ്ണൂർ', district: 'Kannur' },
  16: { acNo: 16, name: 'Sreekandapuram', nameMl: 'ശ്രീകണ്ഠപുരം', district: 'Kannur' },
  // WAYANAD
  17: { acNo: 17, name: 'Mananthavady', nameMl: 'മാനന്തവാടി', district: 'Wayanad' },
  18: { acNo: 18, name: 'Sulthan Bathery', nameMl: 'സുൽത്താൻ ബത്തേരി', district: 'Wayanad' },
  19: { acNo: 19, name: 'Kalpetta', nameMl: 'കൽപ്പറ്റ', district: 'Wayanad' },
  // KOZHIKODE
  20: { acNo: 20, name: 'Thiruvambady', nameMl: 'തിരുവമ്പാടി', district: 'Kozhikode' },
  21: { acNo: 21, name: 'Perambra', nameMl: 'പേരാമ്പ്ര', district: 'Kozhikode' },
  22: { acNo: 22, name: 'Balussery', nameMl: 'ബാലുശ്ശേരി', district: 'Kozhikode' },
  23: { acNo: 23, name: 'Elathur', nameMl: 'ഏലത്തൂർ', district: 'Kozhikode' },
  24: { acNo: 24, name: 'Kozhikode North', nameMl: 'കോഴിക്കോട് നോർത്ത്', district: 'Kozhikode' },
  25: { acNo: 25, name: 'Kozhikode South', nameMl: 'കോഴിക്കോട് സൗത്ത്', district: 'Kozhikode' },
  26: { acNo: 26, name: 'Beypore', nameMl: 'ബേപ്പൂർ', district: 'Kozhikode' },
  27: { acNo: 27, name: 'Kunnamangalam', nameMl: 'കുന്നമംഗലം', district: 'Kozhikode' },
  28: { acNo: 28, name: 'Koduvally', nameMl: 'കൊടുവള്ളി', district: 'Kozhikode' },
  29: { acNo: 29, name: 'Nadapuram', nameMl: 'നടപ്പുറം', district: 'Kozhikode' },
  30: { acNo: 30, name: 'Koyilandy', nameMl: 'കൊയിലാണ്ടി', district: 'Kozhikode' },
  // MALAPPURAM
  31: { acNo: 31, name: 'Wandoor', nameMl: 'വണ്ടൂർ', district: 'Malappuram' },
  32: { acNo: 32, name: 'Manjeri', nameMl: 'മഞ്ചേരി', district: 'Malappuram' },
  33: { acNo: 33, name: 'Tirur', nameMl: 'തിരൂർ', district: 'Malappuram' },
  34: { acNo: 34, name: 'Tanur', nameMl: 'തനൂർ', district: 'Malappuram' },
  35: { acNo: 35, name: 'Tirurangadi', nameMl: 'തിരൂരങ്ങാടി', district: 'Malappuram' },
  36: { acNo: 36, name: 'Malappuram', nameMl: 'മലപ്പുറം', district: 'Malappuram' },
  37: { acNo: 37, name: 'Vengara', nameMl: 'വേങ്ങര', district: 'Malappuram' },
  38: { acNo: 38, name: 'Mankada', nameMl: 'മങ്കട', district: 'Malappuram' },
  39: { acNo: 39, name: 'Perinthalmanna', nameMl: 'പെരിന്തൽമണ്ണ', district: 'Malappuram' },
  40: { acNo: 40, name: 'Eranad', nameMl: 'ഏറനാട്', district: 'Malappuram' },
  41: { acNo: 41, name: 'Kondotty', nameMl: 'കൊണ്ടോട്ടി', district: 'Malappuram' },
  42: { acNo: 42, name: 'Nilambur', nameMl: 'നിലമ്പൂർ', district: 'Malappuram' },
  43: { acNo: 43, name: 'Ponnani', nameMl: 'പൊന്നാനി', district: 'Malappuram' },
  // PALAKKAD
  44: { acNo: 44, name: 'Thrithala', nameMl: 'തൃത്താല', district: 'Palakkad' },
  45: { acNo: 45, name: 'Pattambi', nameMl: 'പട്ടാമ്പി', district: 'Palakkad' },
  46: { acNo: 46, name: 'Shornur', nameMl: 'ഷൊർണൂർ', district: 'Palakkad' },
  47: { acNo: 47, name: 'Ottapalam', nameMl: 'ഒറ്റപ്പാലം', district: 'Palakkad' },
  48: { acNo: 48, name: 'Kongad', nameMl: 'കൊങ്ങാട്', district: 'Palakkad' },
  49: { acNo: 49, name: 'Mannarkkad', nameMl: 'മണ്ണാർക്കാട്', district: 'Palakkad' },
  50: { acNo: 50, name: 'Malampuzha', nameMl: 'മലമ്പുഴ', district: 'Palakkad' },
  51: { acNo: 51, name: 'Palakkad', nameMl: 'പാലക്കാട്', district: 'Palakkad' },
  52: { acNo: 52, name: 'Chittur', nameMl: 'ചിറ്റൂർ', district: 'Palakkad' },
  53: { acNo: 53, name: 'Nenmara', nameMl: 'നെന്മാറ', district: 'Palakkad' },
  54: { acNo: 54, name: 'Alathur', nameMl: 'ആലത്തൂർ', district: 'Palakkad' },
  // THRISSUR
  55: { acNo: 55, name: 'Chelakkara', nameMl: 'ചേലക്കര', district: 'Thrissur' },
  56: { acNo: 56, name: 'Kunnamkulam', nameMl: 'കുന്നംകുളം', district: 'Thrissur' },
  57: { acNo: 57, name: 'Guruvayur', nameMl: 'ഗുരുവായൂർ', district: 'Thrissur' },
  58: { acNo: 58, name: 'Manalur', nameMl: 'മണലൂർ', district: 'Thrissur' },
  59: { acNo: 59, name: 'Wadakkanchery', nameMl: 'വടക്കാഞ്ചേരി', district: 'Thrissur' },
  60: { acNo: 60, name: 'Ollur', nameMl: 'ഒല്ലൂർ', district: 'Thrissur' },
  61: { acNo: 61, name: 'Thrissur', nameMl: 'തൃശൂർ', district: 'Thrissur' },
  62: { acNo: 62, name: 'Nattika', nameMl: 'നട്ടിക', district: 'Thrissur' },
  63: { acNo: 63, name: 'Kaipamangalam', nameMl: 'കൈപ്പമംഗലം', district: 'Thrissur' },
  64: { acNo: 64, name: 'Irinjalakuda', nameMl: 'ഇരിഞ്ഞാലക്കുട', district: 'Thrissur' },
  65: { acNo: 65, name: 'Puthukkad', nameMl: 'പുതുക്കാട്', district: 'Thrissur' },
  66: { acNo: 66, name: 'Chalakudy', nameMl: 'ചാലക്കുടി', district: 'Thrissur' },
  67: { acNo: 67, name: 'Kodungallur', nameMl: 'കൊടുങ്ങല്ലൂർ', district: 'Thrissur' },
  // ERNAKULAM
  68: { acNo: 68, name: 'Perumbavoor', nameMl: 'പെരുമ്പാവൂർ', district: 'Ernakulam' },
  69: { acNo: 69, name: 'Angamaly', nameMl: 'അങ്കമാലി', district: 'Ernakulam' },
  70: { acNo: 70, name: 'Aluva', nameMl: 'ആലുവ', district: 'Ernakulam' },
  71: { acNo: 71, name: 'Kalamassery', nameMl: 'കളമശ്ശേരി', district: 'Ernakulam' },
  72: { acNo: 72, name: 'Paravur', nameMl: 'പറവൂർ', district: 'Ernakulam' },
  73: { acNo: 73, name: 'Vypin', nameMl: 'വൈപ്പിൻ', district: 'Ernakulam' },
  74: { acNo: 74, name: 'Kochi', nameMl: 'കൊച്ചി', district: 'Ernakulam' },
  75: { acNo: 75, name: 'Thrippunithura', nameMl: 'തൃപ്പൂണിത്തുറ', district: 'Ernakulam' },
  76: { acNo: 76, name: 'Ernakulam', nameMl: 'എറണാകുളം', district: 'Ernakulam' },
  77: { acNo: 77, name: 'Thrikkakara', nameMl: 'തൃക്കാക്കര', district: 'Ernakulam' },
  78: { acNo: 78, name: 'Kunnathunad', nameMl: 'കുന്നത്തുനാട്', district: 'Ernakulam' },
  79: { acNo: 79, name: 'Piravom', nameMl: 'പിറവം', district: 'Ernakulam' },
  80: { acNo: 80, name: 'Muvattupuzha', nameMl: 'മൂവാറ്റുപുഴ', district: 'Ernakulam' },
  81: { acNo: 81, name: 'Kothamangalam', nameMl: 'കോതമംഗലം', district: 'Ernakulam' },
  // IDUKKI
  82: { acNo: 82, name: 'Devikulam', nameMl: 'ദേവികുളം', district: 'Idukki' },
  83: { acNo: 83, name: 'Udumbanchola', nameMl: 'ഉടുമ്പൻചോല', district: 'Idukki' },
  84: { acNo: 84, name: 'Thodupuzha', nameMl: 'തൊടുപുഴ', district: 'Idukki' },
  85: { acNo: 85, name: 'Idukki', nameMl: 'ഇടുക്കി', district: 'Idukki' },
  86: { acNo: 86, name: 'Peerumade', nameMl: 'പീരുമേട്', district: 'Idukki' },
  // KOTTAYAM
  87: { acNo: 87, name: 'Pala', nameMl: 'പാലാ', district: 'Kottayam' },
  88: { acNo: 88, name: 'Kaduthuruthy', nameMl: 'കടുത്തുരുത്തി', district: 'Kottayam' },
  89: { acNo: 89, name: 'Vaikom', nameMl: 'വൈക്കം', district: 'Kottayam' },
  90: { acNo: 90, name: 'Ettumanoor', nameMl: 'എട്ടുമാനൂർ', district: 'Kottayam' },
  91: { acNo: 91, name: 'Kottayam', nameMl: 'കോട്ടയം', district: 'Kottayam' },
  92: { acNo: 92, name: 'Puthuppally', nameMl: 'പുതുപ്പള്ളി', district: 'Kottayam' },
  93: { acNo: 93, name: 'Changanassery', nameMl: 'ചങ്ങനാശ്ശേരി', district: 'Kottayam' },
  94: { acNo: 94, name: 'Kanjirappally', nameMl: 'കാഞ്ഞിരപ്പള്ളി', district: 'Kottayam' },
  95: { acNo: 95, name: 'Poonjar', nameMl: 'പൂഞ്ഞാർ', district: 'Kottayam' },
  // ALAPPUZHA
  96: { acNo: 96, name: 'Aroor', nameMl: 'അരൂർ', district: 'Alappuzha' },
  97: { acNo: 97, name: 'Cherthala', nameMl: 'ചേർത്തല', district: 'Alappuzha' },
  98: { acNo: 98, name: 'Alappuzha', nameMl: 'ആലപ്പുഴ', district: 'Alappuzha' },
  99: { acNo: 99, name: 'Ambalappuzha', nameMl: 'അമ്പലപ്പുഴ', district: 'Alappuzha' },
  100: { acNo: 100, name: 'Kuttanad', nameMl: 'കുട്ടനാട്', district: 'Alappuzha' },
  101: { acNo: 101, name: 'Haripad', nameMl: 'ഹരിപ്പാട്', district: 'Alappuzha' },
  102: { acNo: 102, name: 'Kayamkulam', nameMl: 'കായംകുളം', district: 'Alappuzha' },
  103: { acNo: 103, name: 'Mavelikkara', nameMl: 'മാവേലിക്കര', district: 'Alappuzha' },
  104: { acNo: 104, name: 'Chengannur', nameMl: 'ചെങ്ങന്നൂർ', district: 'Alappuzha' },
  // PATHANAMTHITTA
  105: { acNo: 105, name: 'Thiruvalla', nameMl: 'തിരുവല്ല', district: 'Pathanamthitta' },
  106: { acNo: 106, name: 'Ranni', nameMl: 'റാന്നി', district: 'Pathanamthitta' },
  107: { acNo: 107, name: 'Aranmula', nameMl: 'ആറന്മുള', district: 'Pathanamthitta' },
  108: { acNo: 108, name: 'Konni', nameMl: 'കോന്നി', district: 'Pathanamthitta' },
  109: { acNo: 109, name: 'Adoor', nameMl: 'അടൂർ', district: 'Pathanamthitta' },
  // KOLLAM
  110: { acNo: 110, name: 'Karunagappally', nameMl: 'കരുനാഗപ്പള്ളി', district: 'Kollam' },
  111: { acNo: 111, name: 'Chavara', nameMl: 'ചവറ', district: 'Kollam' },
  112: { acNo: 112, name: 'Kunnathur', nameMl: 'കുന്നത്തൂർ', district: 'Kollam' },
  113: { acNo: 113, name: 'Kottarakkara', nameMl: 'കൊട്ടാരക്കര', district: 'Kollam' },
  114: { acNo: 114, name: 'Pathanapuram', nameMl: 'പത്തനാപുരം', district: 'Kollam' },
  115: { acNo: 115, name: 'Punalur', nameMl: 'പുനലൂർ', district: 'Kollam' },
  116: { acNo: 116, name: 'Chadayamangalam', nameMl: 'ചടയമംഗലം', district: 'Kollam' },
  117: { acNo: 117, name: 'Kundara', nameMl: 'കുണ്ടറ', district: 'Kollam' },
  118: { acNo: 118, name: 'Kollam', nameMl: 'കൊല്ലം', district: 'Kollam' },
  119: { acNo: 119, name: 'Eravipuram', nameMl: 'ഇരവിപുരം', district: 'Kollam' },
  120: { acNo: 120, name: 'Chathannoor', nameMl: 'ചാത്തന്നൂർ', district: 'Kollam' },
  // THIRUVANANTHAPURAM
  121: { acNo: 121, name: 'Varkala', nameMl: 'വർക്കല', district: 'Thiruvananthapuram' },
  122: { acNo: 122, name: 'Attingal', nameMl: 'ആറ്റിങ്ങൽ', district: 'Thiruvananthapuram' },
  123: { acNo: 123, name: 'Chirayinkeezhu', nameMl: 'ചിറയിൻകീഴ്', district: 'Thiruvananthapuram' },
  124: { acNo: 124, name: 'Nedumangad', nameMl: 'നെടുമങ്ങാട്', district: 'Thiruvananthapuram' },
  125: { acNo: 125, name: 'Vamanapuram', nameMl: 'വാമനപുരം', district: 'Thiruvananthapuram' },
  126: { acNo: 126, name: 'Kazhakkoottam', nameMl: 'കഴക്കൂട്ടം', district: 'Thiruvananthapuram' },
  127: { acNo: 127, name: 'Vattiyoorkavu', nameMl: 'വട്ടിയൂർക്കാവ്', district: 'Thiruvananthapuram' },
  128: { acNo: 128, name: 'Thiruvananthapuram', nameMl: 'തിരുവനന്തപുരം', district: 'Thiruvananthapuram' },
  129: { acNo: 129, name: 'Nemom', nameMl: 'നേമം', district: 'Thiruvananthapuram' },
  130: { acNo: 130, name: 'Aruvikkara', nameMl: 'അരുവിക്കര', district: 'Thiruvananthapuram' },
  131: { acNo: 131, name: 'Parassala', nameMl: 'പാറശ്ശാല', district: 'Thiruvananthapuram' },
  132: { acNo: 132, name: 'Kattakkada', nameMl: 'കാട്ടാക്കട', district: 'Thiruvananthapuram' },
  133: { acNo: 133, name: 'Kovalam', nameMl: 'കോവളം', district: 'Thiruvananthapuram' },
  134: { acNo: 134, name: 'Neyyattinkara', nameMl: 'നെയ്യാറ്റിൻകര', district: 'Thiruvananthapuram' },
};
